import { TypoXLarge, TypoBase } from "@/shared/ui";

const ContentPolicy = () => {
  return (
    <div className="flex h-full flex-col overflow-hidden">
      {/* Content */}
      <div className="flex-1 overflow-y-auto">
        <div className="mx-auto w-full max-w-[587px] px-4 py-4 md:py-20">
          {/* Desktop title - hidden on mobile */}
          <TypoXLarge className="text-text-primary mb-8 hidden font-semibold md:block">
            Content Policy
          </TypoXLarge>

          {/* Last updated */}
          <TypoBase className="text-text-placeholder mb-6">
            Last updated: May 19th, 2025
          </TypoBase>

          {/* Policy content */}
          <div className="text-text-primary prose prose-invert max-w-none text-base">
            <div className="mb-8"></div>
            <p className="text-text-placeholder mb-6">
              We, harpy chat inc., are dedicated to ensuring that our
              application is utilized responsibly and safely by our users.
            </p>

            <h3 className="mt-8 mb-4 text-xl font-semibold">
              1. Content Responsibility
            </h3>
            <div className="mb-8">
              <hr className="border-border-divider my-6" />
            </div>
            <p className="mb-4">
              As a user of the astrsk.ai, you are solely responsible for the
              input prompt and output generated by the AI through text messages,
              voice messages, images, and videos. You are responsible for the
              response based on your selected parameters. You understand and
              agree that harpy chat inc. does not control or endorse the content
              generated by the AI. Consequently, you acknowledge that you are
              fully responsible for the AI-generated output and for your actions
              while using the astrsk.ai.
            </p>
            <p className="mb-4">
              You must ensure that your interactions with the AI comply with
              applicable laws, regulations, our Terms and Policies. You must not
              engage in any illegal, unethical, or harmful activities through
              the astrsk.ai.
            </p>
            <p className="mb-6">
              We prohibit any content that exploits or endangers minors,
              including but not limited to child pornography, sexual
              exploitation, or any form of harm or harassment towards minors, as
              well as any attempt to generate AI content resembling minors or
              exploiting their likeness.
            </p>

            <h3 className="mt-8 mb-4 font-semibold">2. Content Ownership</h3>
            <div className="mb-8">
              <hr className="border-border-divider my-6" />
            </div>
            <p className="mb-6">
              At harpy chat inc., all and any interactions and outcomes between
              users and AI are accessible and manageable solely by its creator
              of the interaction. No one else can access data generated from
              other users. This measure is designed to maintain a respectful and
              secure environment for all users. We strive to become the most
              privacy and data security-centric application in the world of AI
              and we appreciate your cooperation in adhering to our guidelines.
            </p>

            <h3 className="mt-8 mb-4 font-semibold">3. Contact Information</h3>
            <div className="mb-8">
              <hr className="border-border-divider my-6" />
            </div>
            <p className="mb-6">
              If you notice any violation of these Terms, content of any nature,
              or if you have any questions or require further clarification
              regarding our Underage Policy, please contact us at{" "}
              <a
                href="mailto:cyoo@astrsk.ai"
                className="text-primary-strong hover:text-primary-strong/80"
              >
                cyoo@astrsk.ai
              </a>{" "}
              to report.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContentPolicy;
