/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSsoCallbackRouteImport } from './routes/_layout/sso-callback'
import { Route as LayoutSignUpRouteImport } from './routes/_layout/sign-up'
import { Route as LayoutSignInRouteImport } from './routes/_layout/sign-in'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutResetPasswordRouteImport } from './routes/_layout/reset-password'
import { Route as LayoutForgotPasswordRouteImport } from './routes/_layout/forgot-password'
import { Route as LayoutEmailVerificationRouteImport } from './routes/_layout/email-verification'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutSessionsIndexRouteImport } from './routes/_layout/sessions/index'
import { Route as LayoutAssetsIndexRouteImport } from './routes/_layout/assets/index'
import { Route as SharedSessionUuidRouteImport } from './routes/shared/session/$uuid'
import { Route as SharedScenarioUuidRouteImport } from './routes/shared/scenario/$uuid'
import { Route as SharedFlowUuidRouteImport } from './routes/shared/flow/$uuid'
import { Route as SharedCharacterUuidRouteImport } from './routes/shared/character/$uuid'
import { Route as LayoutSettingsProvidersRouteImport } from './routes/_layout/settings/providers'
import { Route as LayoutSessionsNewRouteImport } from './routes/_layout/sessions/new'
import { Route as LayoutSessionsSessionIdRouteImport } from './routes/_layout/sessions/$sessionId'
import { Route as LayoutAuthHubCallbackRouteImport } from './routes/_layout/auth/hub-callback'
import { Route as LayoutAuthCallbackRouteImport } from './routes/_layout/auth/callback'
import { Route as LayoutSettingsLegalIndexRouteImport } from './routes/_layout/settings/legal/index'
import { Route as LayoutSettingsAdvancedIndexRouteImport } from './routes/_layout/settings/advanced/index'
import { Route as LayoutSettingsAccountIndexRouteImport } from './routes/_layout/settings/account/index'
import { Route as LayoutAssetsWorkflowsIndexRouteImport } from './routes/_layout/assets/workflows/index'
import { Route as LayoutAssetsScenariosIndexRouteImport } from './routes/_layout/assets/scenarios/index'
import { Route as LayoutAssetsCharactersIndexRouteImport } from './routes/_layout/assets/characters/index'
import { Route as LayoutSettingsLegalTermsOfServiceRouteImport } from './routes/_layout/settings/legal/terms-of-service'
import { Route as LayoutSettingsLegalRefundPolicyRouteImport } from './routes/_layout/settings/legal/refund-policy'
import { Route as LayoutSettingsLegalPrivacyPolicyRouteImport } from './routes/_layout/settings/legal/privacy-policy'
import { Route as LayoutSettingsLegalOssNoticeRouteImport } from './routes/_layout/settings/legal/oss-notice'
import { Route as LayoutSettingsLegalContentPolicyRouteImport } from './routes/_layout/settings/legal/content-policy'
import { Route as LayoutSettingsAdvancedMigrationHistoryRouteImport } from './routes/_layout/settings/advanced/migration-history'
import { Route as LayoutSettingsAdvancedInitializationLogsRouteImport } from './routes/_layout/settings/advanced/initialization-logs'
import { Route as LayoutSettingsAccountCreditUsageRouteImport } from './routes/_layout/settings/account/credit-usage'
import { Route as LayoutSessionsSettingsSessionIdRouteImport } from './routes/_layout/sessions/settings/$sessionId'
import { Route as LayoutAssetsWorkflowsWorkflowIdRouteImport } from './routes/_layout/assets/workflows/$workflowId'
import { Route as LayoutAssetsScenariosChar123ScenarioIdChar125RouteImport } from './routes/_layout/assets/scenarios/{-$scenarioId}'
import { Route as LayoutAssetsCharactersChar123CharacterIdChar125RouteImport } from './routes/_layout/assets/characters/{-$characterId}'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSsoCallbackRoute = LayoutSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSignUpRoute = LayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSignInRoute = LayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResetPasswordRoute = LayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutForgotPasswordRoute = LayoutForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailVerificationRoute = LayoutEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSessionsIndexRoute = LayoutSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAssetsIndexRoute = LayoutAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => LayoutRoute,
} as any)
const SharedSessionUuidRoute = SharedSessionUuidRouteImport.update({
  id: '/shared/session/$uuid',
  path: '/shared/session/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedScenarioUuidRoute = SharedScenarioUuidRouteImport.update({
  id: '/shared/scenario/$uuid',
  path: '/shared/scenario/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedFlowUuidRoute = SharedFlowUuidRouteImport.update({
  id: '/shared/flow/$uuid',
  path: '/shared/flow/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedCharacterUuidRoute = SharedCharacterUuidRouteImport.update({
  id: '/shared/character/$uuid',
  path: '/shared/character/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsProvidersRoute = LayoutSettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSessionsNewRoute = LayoutSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsSessionIdRoute = LayoutSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthHubCallbackRoute = LayoutAuthHubCallbackRouteImport.update({
  id: '/auth/hub-callback',
  path: '/auth/hub-callback',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthCallbackRoute = LayoutAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsLegalIndexRoute =
  LayoutSettingsLegalIndexRouteImport.update({
    id: '/legal/',
    path: '/legal/',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsAdvancedIndexRoute =
  LayoutSettingsAdvancedIndexRouteImport.update({
    id: '/advanced/',
    path: '/advanced/',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsAccountIndexRoute =
  LayoutSettingsAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutAssetsWorkflowsIndexRoute =
  LayoutAssetsWorkflowsIndexRouteImport.update({
    id: '/assets/workflows/',
    path: '/assets/workflows/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAssetsScenariosIndexRoute =
  LayoutAssetsScenariosIndexRouteImport.update({
    id: '/assets/scenarios/',
    path: '/assets/scenarios/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAssetsCharactersIndexRoute =
  LayoutAssetsCharactersIndexRouteImport.update({
    id: '/assets/characters/',
    path: '/assets/characters/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsLegalTermsOfServiceRoute =
  LayoutSettingsLegalTermsOfServiceRouteImport.update({
    id: '/legal/terms-of-service',
    path: '/legal/terms-of-service',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsLegalRefundPolicyRoute =
  LayoutSettingsLegalRefundPolicyRouteImport.update({
    id: '/legal/refund-policy',
    path: '/legal/refund-policy',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsLegalPrivacyPolicyRoute =
  LayoutSettingsLegalPrivacyPolicyRouteImport.update({
    id: '/legal/privacy-policy',
    path: '/legal/privacy-policy',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsLegalOssNoticeRoute =
  LayoutSettingsLegalOssNoticeRouteImport.update({
    id: '/legal/oss-notice',
    path: '/legal/oss-notice',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsLegalContentPolicyRoute =
  LayoutSettingsLegalContentPolicyRouteImport.update({
    id: '/legal/content-policy',
    path: '/legal/content-policy',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsAdvancedMigrationHistoryRoute =
  LayoutSettingsAdvancedMigrationHistoryRouteImport.update({
    id: '/advanced/migration-history',
    path: '/advanced/migration-history',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsAdvancedInitializationLogsRoute =
  LayoutSettingsAdvancedInitializationLogsRouteImport.update({
    id: '/advanced/initialization-logs',
    path: '/advanced/initialization-logs',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsAccountCreditUsageRoute =
  LayoutSettingsAccountCreditUsageRouteImport.update({
    id: '/account/credit-usage',
    path: '/account/credit-usage',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSessionsSettingsSessionIdRoute =
  LayoutSessionsSettingsSessionIdRouteImport.update({
    id: '/sessions/settings/$sessionId',
    path: '/sessions/settings/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAssetsWorkflowsWorkflowIdRoute =
  LayoutAssetsWorkflowsWorkflowIdRouteImport.update({
    id: '/assets/workflows/$workflowId',
    path: '/assets/workflows/$workflowId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAssetsScenariosChar123ScenarioIdChar125Route =
  LayoutAssetsScenariosChar123ScenarioIdChar125RouteImport.update({
    id: '/assets/scenarios/{-$scenarioId}',
    path: '/assets/scenarios/{-$scenarioId}',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAssetsCharactersChar123CharacterIdChar125Route =
  LayoutAssetsCharactersChar123CharacterIdChar125RouteImport.update({
    id: '/assets/characters/{-$characterId}',
    path: '/assets/characters/{-$characterId}',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/email-verification': typeof LayoutEmailVerificationRoute
  '/forgot-password': typeof LayoutForgotPasswordRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/sign-in': typeof LayoutSignInRoute
  '/sign-up': typeof LayoutSignUpRoute
  '/sso-callback': typeof LayoutSsoCallbackRoute
  '/': typeof LayoutIndexRoute
  '/auth/callback': typeof LayoutAuthCallbackRoute
  '/auth/hub-callback': typeof LayoutAuthHubCallbackRoute
  '/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/sessions/new': typeof LayoutSessionsNewRoute
  '/settings/providers': typeof LayoutSettingsProvidersRoute
  '/shared/character/$uuid': typeof SharedCharacterUuidRoute
  '/shared/flow/$uuid': typeof SharedFlowUuidRoute
  '/shared/scenario/$uuid': typeof SharedScenarioUuidRoute
  '/shared/session/$uuid': typeof SharedSessionUuidRoute
  '/assets': typeof LayoutAssetsIndexRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/assets/characters/{-$characterId}': typeof LayoutAssetsCharactersChar123CharacterIdChar125Route
  '/assets/scenarios/{-$scenarioId}': typeof LayoutAssetsScenariosChar123ScenarioIdChar125Route
  '/assets/workflows/$workflowId': typeof LayoutAssetsWorkflowsWorkflowIdRoute
  '/sessions/settings/$sessionId': typeof LayoutSessionsSettingsSessionIdRoute
  '/settings/account/credit-usage': typeof LayoutSettingsAccountCreditUsageRoute
  '/settings/advanced/initialization-logs': typeof LayoutSettingsAdvancedInitializationLogsRoute
  '/settings/advanced/migration-history': typeof LayoutSettingsAdvancedMigrationHistoryRoute
  '/settings/legal/content-policy': typeof LayoutSettingsLegalContentPolicyRoute
  '/settings/legal/oss-notice': typeof LayoutSettingsLegalOssNoticeRoute
  '/settings/legal/privacy-policy': typeof LayoutSettingsLegalPrivacyPolicyRoute
  '/settings/legal/refund-policy': typeof LayoutSettingsLegalRefundPolicyRoute
  '/settings/legal/terms-of-service': typeof LayoutSettingsLegalTermsOfServiceRoute
  '/assets/characters': typeof LayoutAssetsCharactersIndexRoute
  '/assets/scenarios': typeof LayoutAssetsScenariosIndexRoute
  '/assets/workflows': typeof LayoutAssetsWorkflowsIndexRoute
  '/settings/account': typeof LayoutSettingsAccountIndexRoute
  '/settings/advanced': typeof LayoutSettingsAdvancedIndexRoute
  '/settings/legal': typeof LayoutSettingsLegalIndexRoute
}
export interface FileRoutesByTo {
  '/email-verification': typeof LayoutEmailVerificationRoute
  '/forgot-password': typeof LayoutForgotPasswordRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/sign-in': typeof LayoutSignInRoute
  '/sign-up': typeof LayoutSignUpRoute
  '/sso-callback': typeof LayoutSsoCallbackRoute
  '/': typeof LayoutIndexRoute
  '/auth/callback': typeof LayoutAuthCallbackRoute
  '/auth/hub-callback': typeof LayoutAuthHubCallbackRoute
  '/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/sessions/new': typeof LayoutSessionsNewRoute
  '/settings/providers': typeof LayoutSettingsProvidersRoute
  '/shared/character/$uuid': typeof SharedCharacterUuidRoute
  '/shared/flow/$uuid': typeof SharedFlowUuidRoute
  '/shared/scenario/$uuid': typeof SharedScenarioUuidRoute
  '/shared/session/$uuid': typeof SharedSessionUuidRoute
  '/assets': typeof LayoutAssetsIndexRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/assets/characters/{-$characterId}': typeof LayoutAssetsCharactersChar123CharacterIdChar125Route
  '/assets/scenarios/{-$scenarioId}': typeof LayoutAssetsScenariosChar123ScenarioIdChar125Route
  '/assets/workflows/$workflowId': typeof LayoutAssetsWorkflowsWorkflowIdRoute
  '/sessions/settings/$sessionId': typeof LayoutSessionsSettingsSessionIdRoute
  '/settings/account/credit-usage': typeof LayoutSettingsAccountCreditUsageRoute
  '/settings/advanced/initialization-logs': typeof LayoutSettingsAdvancedInitializationLogsRoute
  '/settings/advanced/migration-history': typeof LayoutSettingsAdvancedMigrationHistoryRoute
  '/settings/legal/content-policy': typeof LayoutSettingsLegalContentPolicyRoute
  '/settings/legal/oss-notice': typeof LayoutSettingsLegalOssNoticeRoute
  '/settings/legal/privacy-policy': typeof LayoutSettingsLegalPrivacyPolicyRoute
  '/settings/legal/refund-policy': typeof LayoutSettingsLegalRefundPolicyRoute
  '/settings/legal/terms-of-service': typeof LayoutSettingsLegalTermsOfServiceRoute
  '/assets/characters': typeof LayoutAssetsCharactersIndexRoute
  '/assets/scenarios': typeof LayoutAssetsScenariosIndexRoute
  '/assets/workflows': typeof LayoutAssetsWorkflowsIndexRoute
  '/settings/account': typeof LayoutSettingsAccountIndexRoute
  '/settings/advanced': typeof LayoutSettingsAdvancedIndexRoute
  '/settings/legal': typeof LayoutSettingsLegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/email-verification': typeof LayoutEmailVerificationRoute
  '/_layout/forgot-password': typeof LayoutForgotPasswordRoute
  '/_layout/reset-password': typeof LayoutResetPasswordRoute
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/_layout/sign-in': typeof LayoutSignInRoute
  '/_layout/sign-up': typeof LayoutSignUpRoute
  '/_layout/sso-callback': typeof LayoutSsoCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/auth/callback': typeof LayoutAuthCallbackRoute
  '/_layout/auth/hub-callback': typeof LayoutAuthHubCallbackRoute
  '/_layout/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/_layout/sessions/new': typeof LayoutSessionsNewRoute
  '/_layout/settings/providers': typeof LayoutSettingsProvidersRoute
  '/shared/character/$uuid': typeof SharedCharacterUuidRoute
  '/shared/flow/$uuid': typeof SharedFlowUuidRoute
  '/shared/scenario/$uuid': typeof SharedScenarioUuidRoute
  '/shared/session/$uuid': typeof SharedSessionUuidRoute
  '/_layout/assets/': typeof LayoutAssetsIndexRoute
  '/_layout/sessions/': typeof LayoutSessionsIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/assets/characters/{-$characterId}': typeof LayoutAssetsCharactersChar123CharacterIdChar125Route
  '/_layout/assets/scenarios/{-$scenarioId}': typeof LayoutAssetsScenariosChar123ScenarioIdChar125Route
  '/_layout/assets/workflows/$workflowId': typeof LayoutAssetsWorkflowsWorkflowIdRoute
  '/_layout/sessions/settings/$sessionId': typeof LayoutSessionsSettingsSessionIdRoute
  '/_layout/settings/account/credit-usage': typeof LayoutSettingsAccountCreditUsageRoute
  '/_layout/settings/advanced/initialization-logs': typeof LayoutSettingsAdvancedInitializationLogsRoute
  '/_layout/settings/advanced/migration-history': typeof LayoutSettingsAdvancedMigrationHistoryRoute
  '/_layout/settings/legal/content-policy': typeof LayoutSettingsLegalContentPolicyRoute
  '/_layout/settings/legal/oss-notice': typeof LayoutSettingsLegalOssNoticeRoute
  '/_layout/settings/legal/privacy-policy': typeof LayoutSettingsLegalPrivacyPolicyRoute
  '/_layout/settings/legal/refund-policy': typeof LayoutSettingsLegalRefundPolicyRoute
  '/_layout/settings/legal/terms-of-service': typeof LayoutSettingsLegalTermsOfServiceRoute
  '/_layout/assets/characters/': typeof LayoutAssetsCharactersIndexRoute
  '/_layout/assets/scenarios/': typeof LayoutAssetsScenariosIndexRoute
  '/_layout/assets/workflows/': typeof LayoutAssetsWorkflowsIndexRoute
  '/_layout/settings/account/': typeof LayoutSettingsAccountIndexRoute
  '/_layout/settings/advanced/': typeof LayoutSettingsAdvancedIndexRoute
  '/_layout/settings/legal/': typeof LayoutSettingsLegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/email-verification'
    | '/forgot-password'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/'
    | '/auth/callback'
    | '/auth/hub-callback'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/settings/providers'
    | '/shared/character/$uuid'
    | '/shared/flow/$uuid'
    | '/shared/scenario/$uuid'
    | '/shared/session/$uuid'
    | '/assets'
    | '/sessions'
    | '/settings/'
    | '/assets/characters/{-$characterId}'
    | '/assets/scenarios/{-$scenarioId}'
    | '/assets/workflows/$workflowId'
    | '/sessions/settings/$sessionId'
    | '/settings/account/credit-usage'
    | '/settings/advanced/initialization-logs'
    | '/settings/advanced/migration-history'
    | '/settings/legal/content-policy'
    | '/settings/legal/oss-notice'
    | '/settings/legal/privacy-policy'
    | '/settings/legal/refund-policy'
    | '/settings/legal/terms-of-service'
    | '/assets/characters'
    | '/assets/scenarios'
    | '/assets/workflows'
    | '/settings/account'
    | '/settings/advanced'
    | '/settings/legal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/email-verification'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/'
    | '/auth/callback'
    | '/auth/hub-callback'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/settings/providers'
    | '/shared/character/$uuid'
    | '/shared/flow/$uuid'
    | '/shared/scenario/$uuid'
    | '/shared/session/$uuid'
    | '/assets'
    | '/sessions'
    | '/settings'
    | '/assets/characters/{-$characterId}'
    | '/assets/scenarios/{-$scenarioId}'
    | '/assets/workflows/$workflowId'
    | '/sessions/settings/$sessionId'
    | '/settings/account/credit-usage'
    | '/settings/advanced/initialization-logs'
    | '/settings/advanced/migration-history'
    | '/settings/legal/content-policy'
    | '/settings/legal/oss-notice'
    | '/settings/legal/privacy-policy'
    | '/settings/legal/refund-policy'
    | '/settings/legal/terms-of-service'
    | '/assets/characters'
    | '/assets/scenarios'
    | '/assets/workflows'
    | '/settings/account'
    | '/settings/advanced'
    | '/settings/legal'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/email-verification'
    | '/_layout/forgot-password'
    | '/_layout/reset-password'
    | '/_layout/settings'
    | '/_layout/sign-in'
    | '/_layout/sign-up'
    | '/_layout/sso-callback'
    | '/_layout/'
    | '/_layout/auth/callback'
    | '/_layout/auth/hub-callback'
    | '/_layout/sessions/$sessionId'
    | '/_layout/sessions/new'
    | '/_layout/settings/providers'
    | '/shared/character/$uuid'
    | '/shared/flow/$uuid'
    | '/shared/scenario/$uuid'
    | '/shared/session/$uuid'
    | '/_layout/assets/'
    | '/_layout/sessions/'
    | '/_layout/settings/'
    | '/_layout/assets/characters/{-$characterId}'
    | '/_layout/assets/scenarios/{-$scenarioId}'
    | '/_layout/assets/workflows/$workflowId'
    | '/_layout/sessions/settings/$sessionId'
    | '/_layout/settings/account/credit-usage'
    | '/_layout/settings/advanced/initialization-logs'
    | '/_layout/settings/advanced/migration-history'
    | '/_layout/settings/legal/content-policy'
    | '/_layout/settings/legal/oss-notice'
    | '/_layout/settings/legal/privacy-policy'
    | '/_layout/settings/legal/refund-policy'
    | '/_layout/settings/legal/terms-of-service'
    | '/_layout/assets/characters/'
    | '/_layout/assets/scenarios/'
    | '/_layout/assets/workflows/'
    | '/_layout/settings/account/'
    | '/_layout/settings/advanced/'
    | '/_layout/settings/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SharedCharacterUuidRoute: typeof SharedCharacterUuidRoute
  SharedFlowUuidRoute: typeof SharedFlowUuidRoute
  SharedScenarioUuidRoute: typeof SharedScenarioUuidRoute
  SharedSessionUuidRoute: typeof SharedSessionUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sso-callback': {
      id: '/_layout/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof LayoutSsoCallbackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sign-up': {
      id: '/_layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof LayoutSignUpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sign-in': {
      id: '/_layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof LayoutSignInRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reset-password': {
      id: '/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof LayoutResetPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/forgot-password': {
      id: '/_layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof LayoutForgotPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-verification': {
      id: '/_layout/email-verification'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof LayoutEmailVerificationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/sessions/': {
      id: '/_layout/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assets/': {
      id: '/_layout/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof LayoutAssetsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/shared/session/$uuid': {
      id: '/shared/session/$uuid'
      path: '/shared/session/$uuid'
      fullPath: '/shared/session/$uuid'
      preLoaderRoute: typeof SharedSessionUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/scenario/$uuid': {
      id: '/shared/scenario/$uuid'
      path: '/shared/scenario/$uuid'
      fullPath: '/shared/scenario/$uuid'
      preLoaderRoute: typeof SharedScenarioUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/flow/$uuid': {
      id: '/shared/flow/$uuid'
      path: '/shared/flow/$uuid'
      fullPath: '/shared/flow/$uuid'
      preLoaderRoute: typeof SharedFlowUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/character/$uuid': {
      id: '/shared/character/$uuid'
      path: '/shared/character/$uuid'
      fullPath: '/shared/character/$uuid'
      preLoaderRoute: typeof SharedCharacterUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings/providers': {
      id: '/_layout/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof LayoutSettingsProvidersRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/sessions/new': {
      id: '/_layout/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof LayoutSessionsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions/$sessionId': {
      id: '/_layout/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof LayoutSessionsSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/auth/hub-callback': {
      id: '/_layout/auth/hub-callback'
      path: '/auth/hub-callback'
      fullPath: '/auth/hub-callback'
      preLoaderRoute: typeof LayoutAuthHubCallbackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/auth/callback': {
      id: '/_layout/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof LayoutAuthCallbackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/legal/': {
      id: '/_layout/settings/legal/'
      path: '/legal'
      fullPath: '/settings/legal'
      preLoaderRoute: typeof LayoutSettingsLegalIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/advanced/': {
      id: '/_layout/settings/advanced/'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof LayoutSettingsAdvancedIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/account/': {
      id: '/_layout/settings/account/'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof LayoutSettingsAccountIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/assets/workflows/': {
      id: '/_layout/assets/workflows/'
      path: '/assets/workflows'
      fullPath: '/assets/workflows'
      preLoaderRoute: typeof LayoutAssetsWorkflowsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assets/scenarios/': {
      id: '/_layout/assets/scenarios/'
      path: '/assets/scenarios'
      fullPath: '/assets/scenarios'
      preLoaderRoute: typeof LayoutAssetsScenariosIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assets/characters/': {
      id: '/_layout/assets/characters/'
      path: '/assets/characters'
      fullPath: '/assets/characters'
      preLoaderRoute: typeof LayoutAssetsCharactersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/legal/terms-of-service': {
      id: '/_layout/settings/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/settings/legal/terms-of-service'
      preLoaderRoute: typeof LayoutSettingsLegalTermsOfServiceRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/legal/refund-policy': {
      id: '/_layout/settings/legal/refund-policy'
      path: '/legal/refund-policy'
      fullPath: '/settings/legal/refund-policy'
      preLoaderRoute: typeof LayoutSettingsLegalRefundPolicyRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/legal/privacy-policy': {
      id: '/_layout/settings/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/settings/legal/privacy-policy'
      preLoaderRoute: typeof LayoutSettingsLegalPrivacyPolicyRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/legal/oss-notice': {
      id: '/_layout/settings/legal/oss-notice'
      path: '/legal/oss-notice'
      fullPath: '/settings/legal/oss-notice'
      preLoaderRoute: typeof LayoutSettingsLegalOssNoticeRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/legal/content-policy': {
      id: '/_layout/settings/legal/content-policy'
      path: '/legal/content-policy'
      fullPath: '/settings/legal/content-policy'
      preLoaderRoute: typeof LayoutSettingsLegalContentPolicyRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/advanced/migration-history': {
      id: '/_layout/settings/advanced/migration-history'
      path: '/advanced/migration-history'
      fullPath: '/settings/advanced/migration-history'
      preLoaderRoute: typeof LayoutSettingsAdvancedMigrationHistoryRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/advanced/initialization-logs': {
      id: '/_layout/settings/advanced/initialization-logs'
      path: '/advanced/initialization-logs'
      fullPath: '/settings/advanced/initialization-logs'
      preLoaderRoute: typeof LayoutSettingsAdvancedInitializationLogsRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/account/credit-usage': {
      id: '/_layout/settings/account/credit-usage'
      path: '/account/credit-usage'
      fullPath: '/settings/account/credit-usage'
      preLoaderRoute: typeof LayoutSettingsAccountCreditUsageRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/sessions/settings/$sessionId': {
      id: '/_layout/sessions/settings/$sessionId'
      path: '/sessions/settings/$sessionId'
      fullPath: '/sessions/settings/$sessionId'
      preLoaderRoute: typeof LayoutSessionsSettingsSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assets/workflows/$workflowId': {
      id: '/_layout/assets/workflows/$workflowId'
      path: '/assets/workflows/$workflowId'
      fullPath: '/assets/workflows/$workflowId'
      preLoaderRoute: typeof LayoutAssetsWorkflowsWorkflowIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assets/scenarios/{-$scenarioId}': {
      id: '/_layout/assets/scenarios/{-$scenarioId}'
      path: '/assets/scenarios/{-$scenarioId}'
      fullPath: '/assets/scenarios/{-$scenarioId}'
      preLoaderRoute: typeof LayoutAssetsScenariosChar123ScenarioIdChar125RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assets/characters/{-$characterId}': {
      id: '/_layout/assets/characters/{-$characterId}'
      path: '/assets/characters/{-$characterId}'
      fullPath: '/assets/characters/{-$characterId}'
      preLoaderRoute: typeof LayoutAssetsCharactersChar123CharacterIdChar125RouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutSettingsRouteChildren {
  LayoutSettingsProvidersRoute: typeof LayoutSettingsProvidersRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutSettingsAccountCreditUsageRoute: typeof LayoutSettingsAccountCreditUsageRoute
  LayoutSettingsAdvancedInitializationLogsRoute: typeof LayoutSettingsAdvancedInitializationLogsRoute
  LayoutSettingsAdvancedMigrationHistoryRoute: typeof LayoutSettingsAdvancedMigrationHistoryRoute
  LayoutSettingsLegalContentPolicyRoute: typeof LayoutSettingsLegalContentPolicyRoute
  LayoutSettingsLegalOssNoticeRoute: typeof LayoutSettingsLegalOssNoticeRoute
  LayoutSettingsLegalPrivacyPolicyRoute: typeof LayoutSettingsLegalPrivacyPolicyRoute
  LayoutSettingsLegalRefundPolicyRoute: typeof LayoutSettingsLegalRefundPolicyRoute
  LayoutSettingsLegalTermsOfServiceRoute: typeof LayoutSettingsLegalTermsOfServiceRoute
  LayoutSettingsAccountIndexRoute: typeof LayoutSettingsAccountIndexRoute
  LayoutSettingsAdvancedIndexRoute: typeof LayoutSettingsAdvancedIndexRoute
  LayoutSettingsLegalIndexRoute: typeof LayoutSettingsLegalIndexRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsProvidersRoute: LayoutSettingsProvidersRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutSettingsAccountCreditUsageRoute: LayoutSettingsAccountCreditUsageRoute,
  LayoutSettingsAdvancedInitializationLogsRoute:
    LayoutSettingsAdvancedInitializationLogsRoute,
  LayoutSettingsAdvancedMigrationHistoryRoute:
    LayoutSettingsAdvancedMigrationHistoryRoute,
  LayoutSettingsLegalContentPolicyRoute: LayoutSettingsLegalContentPolicyRoute,
  LayoutSettingsLegalOssNoticeRoute: LayoutSettingsLegalOssNoticeRoute,
  LayoutSettingsLegalPrivacyPolicyRoute: LayoutSettingsLegalPrivacyPolicyRoute,
  LayoutSettingsLegalRefundPolicyRoute: LayoutSettingsLegalRefundPolicyRoute,
  LayoutSettingsLegalTermsOfServiceRoute:
    LayoutSettingsLegalTermsOfServiceRoute,
  LayoutSettingsAccountIndexRoute: LayoutSettingsAccountIndexRoute,
  LayoutSettingsAdvancedIndexRoute: LayoutSettingsAdvancedIndexRoute,
  LayoutSettingsLegalIndexRoute: LayoutSettingsLegalIndexRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutEmailVerificationRoute: typeof LayoutEmailVerificationRoute
  LayoutForgotPasswordRoute: typeof LayoutForgotPasswordRoute
  LayoutResetPasswordRoute: typeof LayoutResetPasswordRoute
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutSignInRoute: typeof LayoutSignInRoute
  LayoutSignUpRoute: typeof LayoutSignUpRoute
  LayoutSsoCallbackRoute: typeof LayoutSsoCallbackRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAuthCallbackRoute: typeof LayoutAuthCallbackRoute
  LayoutAuthHubCallbackRoute: typeof LayoutAuthHubCallbackRoute
  LayoutSessionsSessionIdRoute: typeof LayoutSessionsSessionIdRoute
  LayoutSessionsNewRoute: typeof LayoutSessionsNewRoute
  LayoutAssetsIndexRoute: typeof LayoutAssetsIndexRoute
  LayoutSessionsIndexRoute: typeof LayoutSessionsIndexRoute
  LayoutAssetsCharactersChar123CharacterIdChar125Route: typeof LayoutAssetsCharactersChar123CharacterIdChar125Route
  LayoutAssetsScenariosChar123ScenarioIdChar125Route: typeof LayoutAssetsScenariosChar123ScenarioIdChar125Route
  LayoutAssetsWorkflowsWorkflowIdRoute: typeof LayoutAssetsWorkflowsWorkflowIdRoute
  LayoutSessionsSettingsSessionIdRoute: typeof LayoutSessionsSettingsSessionIdRoute
  LayoutAssetsCharactersIndexRoute: typeof LayoutAssetsCharactersIndexRoute
  LayoutAssetsScenariosIndexRoute: typeof LayoutAssetsScenariosIndexRoute
  LayoutAssetsWorkflowsIndexRoute: typeof LayoutAssetsWorkflowsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutEmailVerificationRoute: LayoutEmailVerificationRoute,
  LayoutForgotPasswordRoute: LayoutForgotPasswordRoute,
  LayoutResetPasswordRoute: LayoutResetPasswordRoute,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutSignInRoute: LayoutSignInRoute,
  LayoutSignUpRoute: LayoutSignUpRoute,
  LayoutSsoCallbackRoute: LayoutSsoCallbackRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAuthCallbackRoute: LayoutAuthCallbackRoute,
  LayoutAuthHubCallbackRoute: LayoutAuthHubCallbackRoute,
  LayoutSessionsSessionIdRoute: LayoutSessionsSessionIdRoute,
  LayoutSessionsNewRoute: LayoutSessionsNewRoute,
  LayoutAssetsIndexRoute: LayoutAssetsIndexRoute,
  LayoutSessionsIndexRoute: LayoutSessionsIndexRoute,
  LayoutAssetsCharactersChar123CharacterIdChar125Route:
    LayoutAssetsCharactersChar123CharacterIdChar125Route,
  LayoutAssetsScenariosChar123ScenarioIdChar125Route:
    LayoutAssetsScenariosChar123ScenarioIdChar125Route,
  LayoutAssetsWorkflowsWorkflowIdRoute: LayoutAssetsWorkflowsWorkflowIdRoute,
  LayoutSessionsSettingsSessionIdRoute: LayoutSessionsSettingsSessionIdRoute,
  LayoutAssetsCharactersIndexRoute: LayoutAssetsCharactersIndexRoute,
  LayoutAssetsScenariosIndexRoute: LayoutAssetsScenariosIndexRoute,
  LayoutAssetsWorkflowsIndexRoute: LayoutAssetsWorkflowsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SharedCharacterUuidRoute: SharedCharacterUuidRoute,
  SharedFlowUuidRoute: SharedFlowUuidRoute,
  SharedScenarioUuidRoute: SharedScenarioUuidRoute,
  SharedSessionUuidRoute: SharedSessionUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
